language: python

python:
    - "3.8"

addons:
    ssh_known_hosts:
        - 159.89.232.85

services:
    - docker

install:
    - pip install -r databank/requirements.txt
    - sudo apt-get install sshpass
script: pytest -q databank/tests.py

deploy:
  # Build Docker container and push to Docker Hub
  provider: script
  script: bash deploy.sh
  on:
    branch: master
