"""fixing uniqueness 2

Revision ID: 0e82af88a879
Revises: 763c25e0d780
Create Date: 2020-09-22 14:36:34.545751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e82af88a879'
down_revision = '763c25e0d780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_author_first_name', table_name='author')
    op.create_index(op.f('ix_author_first_name'), 'author', ['first_name'], unique=False)
    op.drop_index('ix_author_last_name', table_name='author')
    op.create_index(op.f('ix_author_last_name'), 'author', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_last_name'), table_name='author')
    op.create_index('ix_author_last_name', 'author', ['last_name'], unique=1)
    op.drop_index(op.f('ix_author_first_name'), table_name='author')
    op.create_index('ix_author_first_name', 'author', ['first_name'], unique=1)
    # ### end Alembic commands ###
