"""new columns

Revision ID: 1cdc835263ed
Revises: dbddf979b2dc
Create Date: 2020-07-14 15:43:50.503069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdc835263ed'
down_revision = 'dbddf979b2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peptoid', sa.Column('topology', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_peptoid_topology'), 'peptoid', ['topology'], unique=False)
    op.add_column('residue', sa.Column('CSD', sa.Text(), nullable=True))
    op.add_column('residue', sa.Column('SMILES', sa.Text(), nullable=True))
    op.add_column('residue', sa.Column('pep_type', sa.Text(), nullable=True))
    op.create_index(op.f('ix_residue_CSD'), 'residue', ['CSD'], unique=True)
    op.create_index(op.f('ix_residue_SMILES'), 'residue', ['SMILES'], unique=True)
    op.create_index(op.f('ix_residue_pep_type'), 'residue', ['pep_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_residue_pep_type'), table_name='residue')
    op.drop_index(op.f('ix_residue_SMILES'), table_name='residue')
    op.drop_index(op.f('ix_residue_CSD'), table_name='residue')
    op.drop_column('residue', 'pep_type')
    op.drop_column('residue', 'SMILES')
    op.drop_column('residue', 'CSD')
    op.drop_index(op.f('ix_peptoid_topology'), table_name='peptoid')
    op.drop_column('peptoid', 'topology')
    # ### end Alembic commands ###
