"""model 1

Revision ID: 21dfe37a4440
Revises: 
Create Date: 2020-07-06 22:52:41.484147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21dfe37a4440'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=True)
    op.create_table('peptoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('release', sa.DateTime(), nullable=True),
    sa.Column('experiment', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peptoid_doi'), 'peptoid', ['doi'], unique=True)
    op.create_index(op.f('ix_peptoid_experiment'), 'peptoid', ['experiment'], unique=False)
    op.create_index(op.f('ix_peptoid_release'), 'peptoid', ['release'], unique=True)
    op.create_index(op.f('ix_peptoid_title'), 'peptoid', ['title'], unique=True)
    op.create_table('residue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residue_nomenclature'), 'residue', ['nomenclature'], unique=True)
    op.create_table('peptoid-author',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.id'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'author_id')
    )
    op.create_table('peptoid-residue',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('residue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.id'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['residue.id'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'residue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peptoid-residue')
    op.drop_table('peptoid-author')
    op.drop_index(op.f('ix_residue_nomenclature'), table_name='residue')
    op.drop_table('residue')
    op.drop_index(op.f('ix_peptoid_title'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_release'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_experiment'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_doi'), table_name='peptoid')
    op.drop_table('peptoid')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
