"""peptoid

Revision ID: 2f1fa3a1e805
Revises: 
Create Date: 2020-05-14 14:53:14.642053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1fa3a1e805'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peptoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('chem_identity', sa.String(length=128), nullable=True),
    sa.Column('authors', sa.String(length=128), nullable=True),
    sa.Column('experiment', sa.String(length=64), nullable=True),
    sa.Column('citation', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peptoid_authors'), 'peptoid', ['authors'], unique=True)
    op.create_index(op.f('ix_peptoid_chem_identity'), 'peptoid', ['chem_identity'], unique=True)
    op.create_index(op.f('ix_peptoid_citation'), 'peptoid', ['citation'], unique=True)
    op.create_index(op.f('ix_peptoid_code'), 'peptoid', ['code'], unique=True)
    op.create_index(op.f('ix_peptoid_experiment'), 'peptoid', ['experiment'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peptoid_experiment'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_code'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_citation'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_chem_identity'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_authors'), table_name='peptoid')
    op.drop_table('peptoid')
    # ### end Alembic commands ###
