"""first migration

Revision ID: 66e635f7c324
Revises: 
Create Date: 2020-07-24 20:41:51.413597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e635f7c324'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_first_name'), 'author', ['first_name'], unique=True)
    op.create_index(op.f('ix_author_last_name'), 'author', ['last_name'], unique=True)
    op.create_table('peptoid',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('release', sa.DateTime(), nullable=True),
    sa.Column('experiment', sa.Text(), nullable=True),
    sa.Column('doi', sa.String(length=32), nullable=True),
    sa.Column('topology', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_peptoid_doi'), 'peptoid', ['doi'], unique=True)
    op.create_index(op.f('ix_peptoid_experiment'), 'peptoid', ['experiment'], unique=False)
    op.create_index(op.f('ix_peptoid_image'), 'peptoid', ['image'], unique=True)
    op.create_index(op.f('ix_peptoid_release'), 'peptoid', ['release'], unique=True)
    op.create_index(op.f('ix_peptoid_title'), 'peptoid', ['title'], unique=True)
    op.create_index(op.f('ix_peptoid_topology'), 'peptoid', ['topology'], unique=False)
    op.create_table('residue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.Column('pep_type', sa.Text(), nullable=True),
    sa.Column('CSD', sa.Text(), nullable=True),
    sa.Column('SMILES', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residue_CSD'), 'residue', ['CSD'], unique=False)
    op.create_index(op.f('ix_residue_SMILES'), 'residue', ['SMILES'], unique=False)
    op.create_index(op.f('ix_residue_nomenclature'), 'residue', ['nomenclature'], unique=True)
    op.create_index(op.f('ix_residue_pep_type'), 'residue', ['pep_type'], unique=False)
    op.create_table('peptoid-author',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.code'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'author_id')
    )
    op.create_table('peptoid-residue',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('residue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.code'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['residue.id'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'residue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peptoid-residue')
    op.drop_table('peptoid-author')
    op.drop_index(op.f('ix_residue_pep_type'), table_name='residue')
    op.drop_index(op.f('ix_residue_nomenclature'), table_name='residue')
    op.drop_index(op.f('ix_residue_SMILES'), table_name='residue')
    op.drop_index(op.f('ix_residue_CSD'), table_name='residue')
    op.drop_table('residue')
    op.drop_index(op.f('ix_peptoid_topology'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_title'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_release'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_image'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_experiment'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_doi'), table_name='peptoid')
    op.drop_table('peptoid')
    op.drop_index(op.f('ix_author_last_name'), table_name='author')
    op.drop_index(op.f('ix_author_first_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
