"""authors table

Revision ID: 6b0842eb8d6a
Revises: 
Create Date: 2020-06-18 23:50:25.177975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0842eb8d6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=True)
    op.create_table('peptoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('release', sa.DateTime(), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('experiment', sa.Text(), nullable=True),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peptoid_authors'), 'peptoid', ['authors'], unique=True)
    op.create_index(op.f('ix_peptoid_doi'), 'peptoid', ['doi'], unique=True)
    op.create_index(op.f('ix_peptoid_experiment'), 'peptoid', ['experiment'], unique=True)
    op.create_index(op.f('ix_peptoid_release'), 'peptoid', ['release'], unique=True)
    op.create_index(op.f('ix_peptoid_title'), 'peptoid', ['title'], unique=True)
    op.create_table('peptoid-author',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.id'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'author_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peptoid-author')
    op.drop_index(op.f('ix_peptoid_title'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_release'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_experiment'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_doi'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_authors'), table_name='peptoid')
    op.drop_table('peptoid')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
