"""fixing uniqueness

Revision ID: 763c25e0d780
Revises: 98cc91c15735
Create Date: 2020-09-22 13:14:11.395256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763c25e0d780'
down_revision = '98cc91c15735'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_peptoid_doi', table_name='peptoid')
    op.create_index(op.f('ix_peptoid_doi'), 'peptoid', ['doi'], unique=False)
    op.drop_index('ix_peptoid_release', table_name='peptoid')
    op.create_index(op.f('ix_peptoid_release'), 'peptoid', ['release'], unique=False)
    op.drop_index('ix_peptoid_title', table_name='peptoid')
    op.create_index(op.f('ix_peptoid_title'), 'peptoid', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peptoid_title'), table_name='peptoid')
    op.create_index('ix_peptoid_title', 'peptoid', ['title'], unique=1)
    op.drop_index(op.f('ix_peptoid_release'), table_name='peptoid')
    op.create_index('ix_peptoid_release', 'peptoid', ['release'], unique=1)
    op.drop_index(op.f('ix_peptoid_doi'), table_name='peptoid')
    op.create_index('ix_peptoid_doi', 'peptoid', ['doi'], unique=1)
    # ### end Alembic commands ###
