"""fixing image unique

Revision ID: 98cc91c15735
Revises: 407bce991999
Create Date: 2020-09-22 13:13:17.067697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98cc91c15735'
down_revision = '407bce991999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_peptoid_image', table_name='peptoid')
    op.create_index(op.f('ix_peptoid_image'), 'peptoid', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_peptoid_image'), table_name='peptoid')
    op.create_index('ix_peptoid_image', 'peptoid', ['image'], unique=1)
    # ### end Alembic commands ###
