"""adding monomer structure

Revision ID: 9f1dd7af797b
Revises: 7b0cc79fb0ff
Create Date: 2020-12-11 11:49:14.919334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f1dd7af797b'
down_revision = '7b0cc79fb0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residue', sa.Column('monomer_structure', sa.Text(), nullable=True))
    op.create_index(op.f('ix_residue_monomer_structure'), 'residue', ['monomer_structure'], unique=False)
    op.drop_index('ix_residue_CSD', table_name='residue')
    op.drop_column('residue', 'CSD')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('residue', sa.Column('CSD', sa.TEXT(), nullable=True))
    op.create_index('ix_residue_CSD', 'residue', ['CSD'], unique=False)
    op.drop_index(op.f('ix_residue_monomer_structure'), table_name='residue')
    op.drop_column('residue', 'monomer_structure')
    # ### end Alembic commands ###
