"""many to many model

Revision ID: de40ed0c3bda
Revises: 6b0842eb8d6a
Create Date: 2020-06-29 15:12:12.613810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de40ed0c3bda'
down_revision = '6b0842eb8d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('residue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomenclature', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residue_nomenclature'), 'residue', ['nomenclature'], unique=True)
    op.create_table('peptoid-residue',
    sa.Column('peptoid_id', sa.Integer(), nullable=False),
    sa.Column('residue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['peptoid_id'], ['peptoid.id'], ),
    sa.ForeignKeyConstraint(['residue_id'], ['residue.id'], ),
    sa.PrimaryKeyConstraint('peptoid_id', 'residue_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peptoid-residue')
    op.drop_index(op.f('ix_residue_nomenclature'), table_name='residue')
    op.drop_table('residue')
    # ### end Alembic commands ###
