"""adding structure doi

Revision ID: ec69df775f3a
Revises: 0e82af88a879
Create Date: 2020-09-26 11:52:52.335208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec69df775f3a'
down_revision = '0e82af88a879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peptoid', sa.Column('pub_doi', sa.String(length=32), nullable=True))
    op.add_column('peptoid', sa.Column('struct_doi', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_peptoid_pub_doi'), 'peptoid', ['pub_doi'], unique=False)
    op.create_index(op.f('ix_peptoid_struct_doi'), 'peptoid', ['struct_doi'], unique=False)
    op.drop_index('ix_peptoid_doi', table_name='peptoid')
    op.drop_column('peptoid', 'doi')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peptoid', sa.Column('doi', sa.VARCHAR(length=32), nullable=True))
    op.create_index('ix_peptoid_doi', 'peptoid', ['doi'], unique=False)
    op.drop_index(op.f('ix_peptoid_struct_doi'), table_name='peptoid')
    op.drop_index(op.f('ix_peptoid_pub_doi'), table_name='peptoid')
    op.drop_column('peptoid', 'struct_doi')
    op.drop_column('peptoid', 'pub_doi')
    # ### end Alembic commands ###
